# Generated by Django 3.0.6 on 2020-05-08 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='names')),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64, verbose_name='Event Types')),
                ('description', models.CharField(max_length=128, verbose_name='Descriptions')),
                ('avatar', models.ImageField(max_length=128, upload_to='uploads/')),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Titles')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=256, verbose_name='Descriptions')),
                ('event_date', models.DateTimeField(verbose_name='Events Dates')),
                ('is_over', models.BooleanField()),
                ('in_progress', models.BooleanField()),
                ('location_lon', models.FloatField()),
                ('location_lat', models.FloatField()),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Cities')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventType', verbose_name='Event Types')),
            ],
        ),
    ]
